export const arrIconBest = [
  {
    id:1,
    imageUrl:require("../static/images/best/around-the-globe.png")
  },
  {
    id:2,
    imageUrl:require("../static/images/best/barbershop.png")
  },
  {
    id:3,
    imageUrl:require("../static/images/best/beach-chair.png")
  },
  {
    id:4,
    imageUrl:require("../static/images/best/beach.png")
  },
  {
    id:5,
    imageUrl:require("../static/images/best/beer-glass.png")
  },
  {
    id:6,
    imageUrl:require("../static/images/best/birthday-cake.png")
  },
  {
    id:7,
    imageUrl:require("../static/images/best/cactus-in-pot.png")
  },
  {
    id:8,
    imageUrl:require("../static/images/best/cafe.png")
  },
  {
    id:9,
    imageUrl:require("../static/images/best/confetti.png")
  },
  {
    id:10,
    imageUrl:require("../static/images/best/facial-mask.png")
  },
  {
    id:11,
    imageUrl:require("../static/images/best/ferris-wheel.png")
  },
  {
    id:12,
    imageUrl:require("../static/images/best/firework-explosion.png")
  },
  {
    id:13,
    imageUrl:require("../static/images/best/game-controller.png")
  },
  {
    id:14,
    imageUrl:require("../static/images/best/heart-outline.png")
  },
  {
    id:15,
    imageUrl:require("../static/images/best/heart.png")
  },
  {
    id:16,
    imageUrl:require("../static/images/best/laptop-cleaning.png")
  },
  {
    id:17,
    imageUrl:require("../static/images/best/party-balloons.png")
  },
  {
    id:18,
    imageUrl:require("../static/images/best/popcorn.png")
  },
  {
    id:19,
    imageUrl:require("../static/images/best/read.png")
  },
  {
    id:20,
    imageUrl:require("../static/images/best/relaxed-working-with-a-laptop.png")
  },
  {
    id:21,
    imageUrl:require("../static/images/best/romance.png")
  },
  {
    id:22,
    imageUrl:require("../static/images/best/santa.png")
  },
  {
    id:23,
    imageUrl:require("../static/images/best/scooter.png")
  },
  {
    id:24,
    imageUrl:require("../static/images/best/shopping-basket.png")
  },
  {
    id:25,
    imageUrl:require("../static/images/best/shuttlecock.png")
  },
  {
    id:26,
    imageUrl:require("../static/images/best/stethoscope.png")
  },
  {
    id:27,
    imageUrl:require("../static/images/best/strawberry.png")
  },
  {
    id:28,
    imageUrl:require("../static/images/best/suitcase.png")
  },
  {
    id:29,
    imageUrl:require("../static/images/best/tea.png")
  },
  {
    id:30,
    imageUrl:require("../static/images/best/trainers.png")
  },
  {
    id:31,
    imageUrl:require("../static/images/best/watermelon.png")
  },
]
export const arrIconFavorites = [
  {
    id:1,
    imageUrl:require("../static/images/favorites/badminton-player.png")
  },
  {
    id:2,
    imageUrl:require("../static/images/favorites/barbershop.png")
  },
  {
    id:3,
    imageUrl:require("../static/images/favorites/beer.png")
  },
  {
    id:4,
    imageUrl:require("../static/images/favorites/birthday.png")
  },
  {
    id:5,
    imageUrl:require("../static/images/favorites/broom.png")
  },
  {
    id:6,
    imageUrl:require("../static/images/favorites/cactus.png")
  },
  {
    id:7,
    imageUrl:require("../static/images/favorites/christmas-tree.png")
  },
  {
    id:8,
    imageUrl:require("../static/images/favorites/confetti.png")
  },
  {
    id:9,
    imageUrl:require("../static/images/favorites/country.png")
  },
  {
    id:10,
    imageUrl:require("../static/images/favorites/energy-drink.png")
  },
  {
    id:11,
    imageUrl:require("../static/images/favorites/ferris-wheel.png")
  },
  {
    id:12,
    imageUrl:require("../static/images/favorites/firework-explosion.png")
  },
  {
    id:13,
    imageUrl:require("../static/images/favorites/grocery-bag.png")
  },
  {
    id:14,
    imageUrl:require("../static/images/favorites/health-checkup.png")
  },
  {
    id:15,
    imageUrl:require("../static/images/favorites/housekeeping.png")
  },
  {
    id:16,
    imageUrl:require("../static/images/favorites/man-feeding-chicken.png")
  },
  {
    id:17,
    imageUrl:require("../static/images/favorites/map-marker.png")
  },
  {
    id:18,
    imageUrl:require("../static/images/favorites/nintendo-switch.png")
  },
  {
    id:19,
    imageUrl:require("../static/images/favorites/palm-tree.png")
  },
  {
    id:20,
    imageUrl:require("../static/images/favorites/pink-heart.png")
  },
  {
    id:21,
    imageUrl:require("../static/images/favorites/popcorn.png")
  },
  {
    id:22,
    imageUrl:require("../static/images/favorites/potted-plant.png")
  },
  {
    id:23,
    imageUrl:require("../static/images/favorites/reading.png")
  },
  {
    id:24,
    imageUrl:require("../static/images/favorites/romance.png")
  },
  {
    id:25,
    imageUrl:require("../static/images/favorites/romantic-movies.png")
  },
  {
    id:26,
    imageUrl:require("../static/images/favorites/start.png")
  },
  {
    id:27,
    imageUrl:require("../static/images/favorites/suitcase.png")
  },
  {
    id:28,
    imageUrl:require("../static/images/favorites/traveler.png")
  },
  {
    id:29,
    imageUrl:require("../static/images/favorites/vietnamese-coffee.png")
  },
  {
    id:30,
    imageUrl:require("../static/images/favorites/working-with-a-laptop.png")
  },
  {
    id:31,
    imageUrl:require("../static/images/favorites/wrestling.png")
  },
]