export const arrIconBest = [
  {
    id:1,
    imageUrl:require("../static/images/best/around-the-globe.png")
  },
  {
    id:2,
    imageUrl:require("../static/images/best/barbershop.png")
  },
  {
    id:3,
    imageUrl:require("../static/images/best/beach-chair.png")
  },
  {
    id:4,
    imageUrl:require("../static/images/best/beach.png")
  },
  {
    id:5,
    imageUrl:require("../static/images/best/beer-glass.png")
  },
  {
    id:6,
    imageUrl:require("../static/images/best/birthday-cake.png")
  },
  {
    id:7,
    imageUrl:require("../static/images/best/cactus-in-pot.png")
  },
  {
    id:8,
    imageUrl:require("../static/images/best/cafe.png")
  },
  {
    id:9,
    imageUrl:require("../static/images/best/confetti.png")
  },
  {
    id:10,
    imageUrl:require("../static/images/best/facial-mask.png")
  },
  {
    id:11,
    imageUrl:require("../static/images/best/ferris-wheel.png")
  },
  {
    id:12,
    imageUrl:require("../static/images/best/firework-explosion.png")
  },
  {
    id:13,
    imageUrl:require("../static/images/best/game-controller.png")
  },
  {
    id:14,
    imageUrl:require("../static/images/best/heart-outline.png")
  },
  {
    id:15,
    imageUrl:require("../static/images/best/heart.png")
  },
  {
    id:16,
    imageUrl:require("../static/images/best/laptop-cleaning.png")
  },
  {
    id:17,
    imageUrl:require("../static/images/best/party-balloons.png")
  },
  {
    id:18,
    imageUrl:require("../static/images/best/popcorn.png")
  },
  {
    id:19,
    imageUrl:require("../static/images/best/read.png")
  },
  {
    id:20,
    imageUrl:require("../static/images/best/relaxed-working-with-a-laptop.png")
  },
  {
    id:21,
    imageUrl:require("../static/images/best/romance.png")
  },
  {
    id:22,
    imageUrl:require("../static/images/best/santa.png")
  },
  {
    id:23,
    imageUrl:require("../static/images/best/scooter.png")
  },
  {
    id:24,
    imageUrl:require("../static/images/best/shopping-basket.png")
  },
  {
    id:25,
    imageUrl:require("../static/images/best/shuttlecock.png")
  },
  {
    id:26,
    imageUrl:require("../static/images/best/stethoscope.png")
  },
  {
    id:27,
    imageUrl:require("../static/images/best/strawberry.png")
  },
  {
    id:28,
    imageUrl:require("../static/images/best/suitcase.png")
  },
  {
    id:29,
    imageUrl:require("../static/images/best/tea.png")
  },
  {
    id:30,
    imageUrl:require("../static/images/best/trainers.png")
  },
  {
    id:31,
    imageUrl:require("../static/images/best/watermelon.png")
  },
  {
    id:32,
    imageUrl:require("../static/images/favorites/badminton-player.png")
  },
  {
    id:33,
    imageUrl:require("../static/images/favorites/barbershop.png")
  },
  {
    id:34,
    imageUrl:require("../static/images/favorites/beer.png")
  },
  {
    id:35,
    imageUrl:require("../static/images/favorites/birthday.png")
  },
  {
    id:36,
    imageUrl:require("../static/images/favorites/broom.png")
  },
  {
    id:37,
    imageUrl:require("../static/images/favorites/cactus.png")
  },
  {
    id:38,
    imageUrl:require("../static/images/favorites/christmas-tree.png")
  },
  {
    id:39,
    imageUrl:require("../static/images/favorites/confetti.png")
  },
  {
    id:40,
    imageUrl:require("../static/images/favorites/country.png")
  },
  {
    id:41,
    imageUrl:require("../static/images/favorites/energy-drink.png")
  },
  {
    id:42,
    imageUrl:require("../static/images/favorites/ferris-wheel.png")
  },
  {
    id:43,
    imageUrl:require("../static/images/favorites/firework-explosion.png")
  },
  {
    id:44,
    imageUrl:require("../static/images/favorites/grocery-bag.png")
  },
  {
    id:45,
    imageUrl:require("../static/images/favorites/health-checkup.png")
  },
  {
    id:46,
    imageUrl:require("../static/images/favorites/housekeeping.png")
  },
  {
    id:47,
    imageUrl:require("../static/images/favorites/man-feeding-chicken.png")
  },
  {
    id:48,
    imageUrl:require("../static/images/favorites/map-marker.png")
  },
  {
    id:49,
    imageUrl:require("../static/images/favorites/nintendo-switch.png")
  },
  {
    id:50,
    imageUrl:require("../static/images/favorites/palm-tree.png")
  },
  {
    id:51,
    imageUrl:require("../static/images/favorites/pink-heart.png")
  },
  {
    id:52,
    imageUrl:require("../static/images/favorites/popcorn.png")
  },
  {
    id:53,
    imageUrl:require("../static/images/favorites/potted-plant.png")
  },
  {
    id:54,
    imageUrl:require("../static/images/favorites/reading.png")
  },
  {
    id:55,
    imageUrl:require("../static/images/favorites/romance.png")
  },
  {
    id:56,
    imageUrl:require("../static/images/favorites/romantic-movies.png")
  },
  {
    id:57,
    imageUrl:require("../static/images/favorites/start.png")
  },
  {
    id:58,
    imageUrl:require("../static/images/favorites/suitcase.png")
  },
  {
    id:59,
    imageUrl:require("../static/images/favorites/traveler.png")
  },
  {
    id:60,
    imageUrl:require("../static/images/favorites/vietnamese-coffee.png")
  },
  {
    id:61,
    imageUrl:require("../static/images/favorites/working-with-a-laptop.png")
  },
  {
    id:62,
    imageUrl:require("../static/images/favorites/wrestling.png")
  },
]
